hash-format = "sha256"

[[files]]
file = "config/promotedserver/servers.dat"
hash = "2065c37b24ba0658d9d2a181632952f447caf3c0fd004d7393a17984d73a3f3b"

[[files]]
file = "mods/crossbow_scoping.pw.toml"
hash = "43e86c3651f84ce92b8ec42a631e675fb35b500143cef8a41c7ec76ecf895160"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "6105a557df9c7e66224bb8f710f839295b0b13bd027d1e516baca10a47e8e489"
metafile = true

[[files]]
file = "mods/grind-enchantments.pw.toml"
hash = "575df9a354a2006f7287610b1e8c9111ebb89c2db6dbab34256db6e6870bc927"
metafile = true

[[files]]
file = "mods/laseredstone.pw.toml"
hash = "f00e9036ea245c75305f760c1a9eafbfa0c653119ab8fd394e90ad39f459c6cf"
metafile = true

[[files]]
file = "mods/promotedserver.pw.toml"
hash = "cc53ad43e9b83e554e2ab1991aaa259151a30db78d14e1f011be6391d2a90f2c"
metafile = true

[[files]]
file = "mods/x-bar-theory.pw.toml"
hash = "f4103d58d6d0eec24602dc505ab67d0a6aa5182ad254096818ecaf1f2bafe799"
metafile = true
