name = "Fabric Holiday 25"
author = "Louis, Fabricord"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8929ae5b8aa8cef6fff6127e0bbeefe89eee3df12392825ba2b331e94d2da7b8"

[versions]
fabric = "0.18.0"
minecraft = "1.21.11-rc1"

[options]
acceptable-game-versions = ["1.21.11-pre4"]
